spring:
  application:
    name: Philocoder Api

server:
  port: 8090
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  connection-timeout: 5000

elasticsearch:
  urls: localhost
  port: 9200

management:
  health:
    elasticsearch:
      enabled: false